// <auto-generated />
namespace Survey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
<<<<<<< HEAD:Survey/Migrations/202103261144323_Initial.Designer.cs
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202103261144323_Initial"; }
=======
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
            get { return "202103261343166_init"; }
>>>>>>> 609abbd7e1af9b550c875ee8aa1331262b59c2c4:Survey/Migrations/202103261343166_init.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
