// <auto-generated />
namespace Survey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:Survey/Migrations/202104081124313_init.Designer.cs
            get { return "202104081124313_init"; }
=======
            get { return "202104061433007_init"; }
>>>>>>> 6418c56e83f301ba1104d26c8964ced25c04270f:Survey/Migrations/202104061433007_init.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
